### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by randel** [sshen82/BandNorm#4]
Hi Siqi,

Thanks for the nice package! I have a question regarding the input format below.

chr1        0               chr1    10000  9
chr1    10000   chr1    10000 20

My input is from `HiCcompare::cooler2bedpe` and listed below. It has seven columns instead of five. Can you let me know which start/end matches to your bin column?

chr1    start1     end1 chr2   start2   end2   IF
chr1 220000 230000 chr1 220000 230000  2
chr1 510000 520000 chr1 510000 520000  3

For scGAD, do you only consider cis contact or both cis and trans? Thanks!

**Comment by sshen82** [comment]
Hi,
Thank you for using the package!

Our package is 0-indexed, so the correct input is chr1 start1 chr2 start2 IF. 

For scGAD, currently our method only considers cis contact.

Yours sincerely,
Siqi Shen
