### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by tarak77** [sshen82/BandNorm#7]
Hi Siqi,
roughly, how does the scGAD function work? I started with a gene annotation file but in the output file with scGAD scores, the gene list is less than what I started with.

**Comment by sshen82** [comment]
Hi Tarak,
During the process of scGAD, it will indeed get all the interactions within all the genes, but at the end of this code, it will remove all the genes with 0 counts among all cells. That's why the gene list is shorter. It doesn't do any other filtering.

Yours sincerely,
Siqi Shen

**Comment by tarak77** [comment]
gene with 0 counts among all cells meaning?

**Comment by tarak77** [comment]
ah i see. ty
